apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-actions-customer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: github-actions-customer
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: github-actions-customer
    spec:
      containers:
      - name: github-actions-customer
        image: lakindu23/ctse-customer:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m