name: Docker Build deploy
on:
  push:
    branches: [ main ]

env:
   DEPLOYMENT_NAME: ctse-customer
   PROJECT_ID: ${{ secrets.GKE_PROJECT }}
   GKE_CLUSTER: github-actions-customer
   GKE_ZONE: us-central1-c

#env:
#  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
#  GKE_CLUSTER: github-actions-customer
#  GKE_ZONE: us-central1-c
#  DEPLOYMENT_NAME: github-actions-customer-deployment
#  IMAGE: github-actions-customer-image
jobs:
  setup-build-publish:
    name: Setup build and setup-build-publish
    runs-on: ubuntu-latest
    
    steps:
     - run: echo "Build Started"
     - name: checkoout repository     
       uses: actions/checkout@v3
     - run: echo "Repository cloned to Ubuntu" 

     - name: Login to Docker Hub
       uses: docker/login-action@v2
       with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

     - name: Set up QEMU   
       uses: docker/setup-qemu-action@v2
     - name: Set up Docker Buildx  
       uses: docker/setup-buildx-action@v2
     - name: Build and push
       uses: docker/build-push-action@v3
       with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.DEPLOYMENT_NAME }}:latest

  deploy:
    needs: setup-build-publish
    name: deploy to GCP
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deployment Started"  
        



   